version: "3"

services:
  nxms_database:
    image: "docker.io/library/postgres:latest"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: netxms_db_password
      POSTGRES_DB: netxmsdb
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    networks:
      nxms_bridge:
        aliases:
          - nxms_database
          - pgsql-server
          - dbhost

  pgadmin:
    image: docker.io/dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@fy.loc
      PGADMIN_DEFAULT_PASSWORD: pgadmin_password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "18080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      nxms_bridge:
        aliases:
          - pgadmin
    #links:
    #  - "nxms_database:pgsql-server"

  netxmsd:
    image: docker.io/fahadysf/netxms-server:latest
    environment:
      DB_SERVER: dbhost
      DB_DRIVER: pgsql.ddr
      DB_USER: admin
      DB_NAME: netxmsdb
      DB_PASSWORD: netxms_db_password
      DB_INIT_PGSQL: 0
    ports:
      #- "514:514"
      - "4701:4701"
    volumes:
      - netxms-config:/data
    networks:
      nxms_bridge:
        aliases:
          - netxmsd
    #links:
    #  - "nxms_database:dbhost"

  netxms-webui:
    image: docker.io/fahadysf/netxms-webui:latest
    environment:
      NETXMS_SERVER: netxmsd
    ports:
      - "8010:8080"
    networks:
      nxms_bridge:
        aliases:
          - netxms-webui
    #links:
    #  - "netxmsd:netxmsd"

volumes:
  netxms-config:
  database-data:
  pgadmin-data:

networks:
  nxms_bridge:
